# Scikit-learn - Preprocesamiento de Datos

Este notebook cubre las técnicas de preprocesamiento de datos en scikit-learn: escalado, normalización, codificación de variables categóricas y manejo de valores faltantes.

## Importar Módulos


In [1]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, Normalizer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import PolynomialFeatures
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd


## Escalado de Datos


In [2]:
# Datos de ejemplo
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# StandardScaler: estandarización (media=0, desv. estándar=1)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("StandardScaler:")
print(f"Media: {X_scaled.mean(axis=0)}")
print(f"Desv. estándar: {X_scaled.std(axis=0)}")

# MinMaxScaler: normalización a rango [0, 1]
minmax = MinMaxScaler()
X_minmax = minmax.fit_transform(X)
print("\nMinMaxScaler (rango [0,1]):")
print(X_minmax)

# RobustScaler: usa mediana y rango intercuartílico (robusto a outliers)
robust = RobustScaler()
X_robust = robust.fit_transform(X)
print("\nRobustScaler:")
print(X_robust)

# Normalizer: normaliza cada muestra (fila) a norma unitaria
normalizer = Normalizer()
X_norm = normalizer.fit_transform(X)
print("\nNormalizer (norma unitaria por fila):")
print(X_norm)


StandardScaler:
Media: [0. 0. 0.]
Desv. estándar: [1. 1. 1.]

MinMaxScaler (rango [0,1]):
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]

RobustScaler:
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]

Normalizer (norma unitaria por fila):
[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]
 [0.50257071 0.57436653 0.64616234]]


## Codificación de Variables Categóricas


In [3]:
# LabelEncoder: codifica etiquetas a números (0, 1, 2, ...)
labels = ['rojo', 'verde', 'azul', 'rojo', 'verde']
le = LabelEncoder()
labels_encoded = le.fit_transform(labels)
print("LabelEncoder:")
print(f"Original: {labels}")
print(f"Codificado: {labels_encoded}")
print(f"Clases: {le.classes_}")

# OneHotEncoder: codificación one-hot (binaria)
categories = [['A', 'B', 'C'], ['X', 'Y']]
ohe = OneHotEncoder()
data_cat = [['A', 'X'], ['B', 'Y'], ['C', 'X']]
data_encoded = ohe.fit_transform(data_cat).toarray()
print("\nOneHotEncoder:")
print(data_encoded)
print(f"Nombres de características: {ohe.get_feature_names_out()}")

# OrdinalEncoder: codificación ordinal (similar a LabelEncoder pero para múltiples columnas)
oe = OrdinalEncoder()
data_ordinal = oe.fit_transform(data_cat)
print("\nOrdinalEncoder:")
print(data_ordinal)


LabelEncoder:
Original: ['rojo', 'verde', 'azul', 'rojo', 'verde']
Codificado: [1 2 0 1 2]
Clases: ['azul' 'rojo' 'verde']

OneHotEncoder:
[[1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0.]]
Nombres de características: ['x0_A' 'x0_B' 'x0_C' 'x1_X' 'x1_Y']

OrdinalEncoder:
[[0. 0.]
 [1. 1.]
 [2. 0.]]


## Manejo de Valores Faltantes


In [4]:
# Datos con valores faltantes
X_missing = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])

# SimpleImputer: imputación de valores faltantes
# Estrategias: 'mean', 'median', 'most_frequent', 'constant'
imputer_mean = SimpleImputer(strategy='mean')
X_imputed = imputer_mean.fit_transform(X_missing)
print("SimpleImputer (media):")
print(X_imputed)

imputer_median = SimpleImputer(strategy='median')
X_imputed_median = imputer_median.fit_transform(X_missing)
print("\nSimpleImputer (mediana):")
print(X_imputed_median)

imputer_constant = SimpleImputer(strategy='constant', fill_value=0)
X_imputed_const = imputer_constant.fit_transform(X_missing)
print("\nSimpleImputer (constante=0):")
print(X_imputed_const)


SimpleImputer (media):
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]

SimpleImputer (mediana):
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]

SimpleImputer (constante=0):
[[1. 2. 0.]
 [4. 0. 6.]
 [7. 8. 9.]]


## Transformaciones Polinómicas


In [5]:
# PolynomialFeatures: genera características polinómicas
X = np.array([[2, 3], [4, 5]])

# Grado 2
poly = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X)
print("PolynomialFeatures (grado 2):")
print(f"Original shape: {X.shape}")
print(f"Polinómico shape: {X_poly.shape}")
print(X_poly)
print(f"Nombres: {poly.get_feature_names_out()}")

# Con sesgo (bias)
poly_bias = PolynomialFeatures(degree=2, include_bias=True)
X_poly_bias = poly_bias.fit_transform(X)
print("\nCon bias (columna de unos):")
print(X_poly_bias)


PolynomialFeatures (grado 2):
Original shape: (2, 2)
Polinómico shape: (2, 5)
[[ 2.  3.  4.  6.  9.]
 [ 4.  5. 16. 20. 25.]]
Nombres: ['x0' 'x1' 'x0^2' 'x0 x1' 'x1^2']

Con bias (columna de unos):
[[ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]


## Pipeline de Preprocesamiento


In [6]:
from sklearn.pipeline import Pipeline

# Crear un pipeline de preprocesamiento
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
    ('poly', PolynomialFeatures(degree=2, include_bias=False))
])

# Aplicar pipeline
X_example = np.array([[1, 2], [3, np.nan], [5, 6]])
X_processed = pipeline.fit_transform(X_example)
print("Pipeline de preprocesamiento:")
print(f"Shape original: {X_example.shape}")
print(f"Shape procesado: {X_processed.shape}")
print(X_processed)


Pipeline de preprocesamiento:
Shape original: (3, 2)
Shape procesado: (3, 5)
[[-1.22474487 -1.22474487  1.5         1.5         1.5       ]
 [ 0.          0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.5         1.5         1.5       ]]
