# NumPy - Indexación y Slicing

Este notebook cubre cómo acceder y modificar elementos en arrays de NumPy: indexación básica, fancy indexing, modificación y concatenación.

## Indexación Básica


In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Indexación simple
arr[0]        # 10 (primer elemento)
arr[-1]       # 50 (último elemento)

# Slicing
arr[1:4]      # [20, 30, 40]
arr[:3]       # [10, 20, 30] (primeros 3)
arr[2:]       # [30, 40, 50] (desde índice 2)
arr[::2]      # [10, 30, 50] (cada 2 elementos)

# Arrays 2D
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz[0, 0]      # 1 (fila 0, columna 0)
matriz[1, 2]      # 6 (fila 1, columna 2)
matriz[0]         # [1, 2, 3] (primera fila completa)
matriz[:, 0]      # [1, 4, 7] (primera columna completa)
matriz[1:3, 1:3]  # [[5, 6], [8, 9]] (submatriz)


array([[5, 6],
       [8, 9]])

## Fancy Indexing (Indexación Avanzada)


In [7]:
arr = np.array([10, 20, 30, 40, 50])

# Indexación con lista de índices
indices = [0, 2, 4]
arr[indices]  # [10, 30, 50]

# Indexación booleana
mask = arr > 30
arr[mask]     # [40, 50]
arr[arr > 30] # [40, 50] (forma abreviada)

# Múltiples condiciones
arr[(arr > 20) & (arr < 50)]  # [30, 40] (usar &, no and)
arr[(arr < 20) | (arr > 40)]  # [10, 50] (usar |, no or)

# Arrays 2D
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz[[0, 2], [0, 2]]  # [1, 9] (elementos (0,0) y (2,2))
matriz[[0, 2]]          # [[1, 2, 3], [7, 8, 9]] (filas 0 y 2)
matriz[:, [0, 2]]       # [[1, 3], [4, 6], [7, 9]] (columnas 0 y 2)


array([[1, 3],
       [4, 6],
       [7, 9]])

## Modificación de Arrays


In [8]:
arr = np.array([1, 2, 3, 4, 5])

# Modificar elementos
arr[0] = 10           # [10, 2, 3, 4, 5]
arr[1:3] = [20, 30]   # [10, 20, 30, 4, 5]

# Modificar con máscara booleana
arr[arr > 3] = 0      # [10, 20, 30, 0, 0]

# Copia vs vista - Demostración
arr_original = np.array([1, 2, 3, 4, 5])

# Vista: los cambios afectan al original
vista = arr_original[1:4]  # [2, 3, 4]
vista[0] = 99  # Modificar la vista
print(f"Array original después de modificar vista: {arr_original}")  # [1, 99, 3, 4, 5]

# Copia: los cambios NO afectan al original
arr_original2 = np.array([1, 2, 3, 4, 5])
copia = arr_original2[1:4].copy()  # Copia independiente
copia[0] = 99  # Modificar la copia
print(f"Array original después de modificar copia: {arr_original2}")  # [1, 2, 3, 4, 5] (sin cambios)

# Arrays 2D
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz[0, 0] = 10     # Modificar elemento
matriz[0] = [10, 20, 30]  # Modificar fila completa
matriz[:, 1] = 0      # Modificar columna completa


Array original después de modificar vista: [ 1 99  3  4  5]
Array original después de modificar copia: [1 2 3 4 5]


## Concatenación y División


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenar
np.concatenate([a, b])           # [1, 2, 3, 4, 5, 6]
np.concatenate([a, b], axis=0)   # Mismo resultado

# Apilar
np.vstack([a, b])                # Apilar verticalmente (filas)
np.hstack([a, b])                # Apilar horizontalmente (columnas)

# Dividir
arr = np.array([1, 2, 3, 4, 5, 6])
np.split(arr, 3)                 # Dividir en 3 partes iguales
np.split(arr, [2, 4])            # Dividir en índices [2, 4]

# Para arrays 2D
matriz = np.array([[1, 2], [3, 4], [5, 6]])
np.vsplit(matriz, 3)             # Dividir verticalmente
np.hsplit(matriz, 2)             # Dividir horizontalmente


[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]