# NumPy - Operaciones

Este notebook cubre las operaciones con arrays de NumPy: operaciones aritméticas, producto matricial, broadcasting y funciones de agregación.

## Operaciones Aritméticas


In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Operaciones elemento a elemento
a + b        # [6, 8, 10, 12]
a - b        # [-4, -4, -4, -4]
np.subtract(a, b)  # Resta (función)
a * b        # [5, 12, 21, 32] (elemento a elemento, NO producto matricial)
a / b        # [0.2, 0.333..., 0.428..., 0.5]
np.divide(a, b)    # División (función)
a ** 2       # [1, 4, 9, 16]
a % 2        # [1, 0, 1, 0]

# Operaciones con escalares
a + 10       # [11, 12, 13, 14]
b + a        # Suma con broadcasting
np.add(b, a)  # Suma (función)
a * 2        # [2, 4, 6, 8]
np.multiply(a, b)  # Multiplicación (función)
a ** 2       # [1, 4, 9, 16]

# Funciones universales (ufuncs) - Operaciones aritméticas
np.add(a, b)      # Suma
np.subtract(a, b) # Resta
np.multiply(a, b) # Multiplicación
np.divide(a, b)   # División
np.power(a, 2)    # Potencia

# Funciones matemáticas elementales
np.sqrt(b)        # Raíz cuadrada
np.exp(b)         # Exponencial (e^x)
np.sin(a)         # Seno
np.cos(b)         # Coseno elemento a elemento
np.log(a)         # Logaritmo natural elemento a elemento
np.abs(a)         # Valor absoluto

# Producto punto (dot product)
e = np.array([[7, 7], [7, 7]])
f = np.array([[1, 0], [0, 1]])
e.dot(f)          # Producto punto: [[7., 7.], [7., 7.]]


array([[7, 7],
       [7, 7]])

## Producto Matricial


In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Producto matricial (dot product)
np.dot(a, b)      # Producto matricial
a @ b             # Operador @ (Python 3.5+)

# Producto elemento a elemento
a * b             # Multiplicación elemento a elemento

# Producto interno
np.inner(a, b)    # Producto interno

# Producto externo
np.outer([1, 2, 3], [4, 5, 6])

# Transpuesta
a.T               # Transpuesta
np.transpose(a)   # Transpuesta


array([[1, 3],
       [2, 4]])

## Broadcasting


In [3]:
# Broadcasting permite operaciones entre arrays de diferentes formas

# Ejemplo 1: Array 1D con escalar
arr = np.array([1, 2, 3, 4])
arr + 10  # [11, 12, 13, 14]

# Ejemplo 2: Array 2D con 1D
matriz = np.array([[1, 2, 3], [4, 5, 6]])  # (2, 3)
vector = np.array([10, 20, 30])            # (3,)
matriz + vector  # Broadcasting: [10,20,30] se replica para cada fila

# Ejemplo 3: Array 2D con columna
columna = np.array([[10], [20]])           # (2, 1)
matriz + columna  # Broadcasting: columna se replica para cada columna

# Reglas de broadcasting:
# 1. Si los arrays tienen diferente número de dimensiones, se añaden 1s a la izquierda
# 2. Arrays con tamaño 1 en alguna dimensión se comportan como si tuvieran ese tamaño
# 3. Arrays deben tener el mismo tamaño en dimensiones compatibles


array([[11, 12, 13],
       [24, 25, 26]])

## Funciones de Agregación


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Estadísticas básicas
np.sum(arr)           # 21 (suma total)
arr.sum()             # Equivalente
np.mean(arr)          # 3.5 (promedio)
arr.mean()            # Equivalente
np.std(arr)           # Desviación estándar
np.var(arr)           # Varianza
np.min(arr)           # 1 (mínimo)
arr.min()             # Equivalente
np.max(arr)           # 6 (máximo)
arr.max()             # Equivalente
np.median(arr)        # Mediana

# Por eje (axis)
np.sum(arr, axis=0)   # Suma por columnas: [5, 7, 9]
arr.sum(axis=0)       # Equivalente
np.sum(arr, axis=1)   # Suma por filas: [6, 15]
arr.sum(axis=1)       # Equivalente
arr.max(axis=0)       # Máximo por columnas
arr.min(axis=0)       # Mínimo por columnas
arr.cumsum(axis=1)    # Suma acumulada por filas
np.mean(arr, axis=0)  # Promedio por columnas

# Otras funciones
np.prod(arr)          # Producto de todos los elementos
np.cumsum(arr)        # Suma acumulada (1D)
arr.cumsum(axis=1)    # Suma acumulada por eje
np.cumprod(arr)       # Producto acumulado
np.argmin(arr)        # Índice del mínimo (aplanado)
np.argmax(arr)        # Índice del máximo (aplanado)
np.any(arr > 3)       # True si algún elemento cumple condición
np.all(arr > 0)       # True si todos los elementos cumplen condición
np.corrcoef(arr)      # Coeficiente de correlación


array([[1., 1.],
       [1., 1.]])