# NumPy - Indexación y Slicing

Este notebook cubre cómo **seleccionar**, **editar** y **eliminar** en arrays de NumPy: indexación básica, rangos de filas y columnas, fancy indexing, modificación (sobrescribir y copias), eliminar filas/columnas/elementos y concatenación.

## Indexación Básica


In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
b = np.array([[1.5, 2, 3], [4, 5, 6]])
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)

# Indexación simple
arr[2]        # 30 (elemento en índice 2)
arr[0]        # 10 (primer elemento)
arr[-1]       # 50 (último elemento)

# Slicing
arr[0:2]      # [10, 20] (elementos en índices 0 y 1)
arr[1:4]      # [20, 30, 40]
arr[:3]       # [10, 20, 30] (primeros 3)
arr[2:]       # [30, 40, 50] (desde índice 2)
arr[::2]      # [10, 30, 50] (cada 2 elementos)
arr[::-1]     # [50, 40, 30, 20, 10] (array invertido)

# Arrays 2D
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b[1, 2]       # 6.0 (elemento en fila 1, columna 2, equivalente a b[1][2])
matriz[0, 0]      # 1 (fila 0, columna 0)
matriz[1, 2]      # 6 (fila 1, columna 2)
matriz[0]         # [1, 2, 3] (primera fila completa)
matriz[:1]        # [[1, 2, 3]] (todas las filas hasta la 1, equivalente a matriz[0:1, :])
b[0:2, 1]     # [2.0, 5.0] (elementos en filas 0 y 1, columna 1)
matriz[:, 0]      # [1, 4, 7] (primera columna completa)
matriz[1:3, 1:3]  # [[5, 6], [8, 9]] (submatriz)

# Arrays 3D
c[1, ...]     # [[[3., 2., 1.], [4., 5., 6.]]] (mismo que c[1, :, :])
c[1]          # Equivalente a c[1, ...]


array([[3., 2., 1.],
       [4., 5., 6.]])

## Fancy Indexing (Indexación Avanzada)


In [2]:
arr = np.array([10, 20, 30, 40, 50])
b = np.array([[1.5, 2, 3], [4, 5, 6]])

# Indexación con lista de índices
indices = [0, 2, 4]
arr[indices]  # [10, 30, 50]

# Indexación booleana
mask = arr > 30
arr[mask]     # [40, 50]
arr[arr > 30] # [40, 50] (forma abreviada)
arr[arr < 25]  # [10, 20] (elementos menores que 25)

# Múltiples condiciones
arr[(arr > 20) & (arr < 50)]  # [30, 40] (usar &, no and)
arr[(arr < 20) | (arr > 40)]  # [10, 50] (usar |, no or)

# Arrays 2D - Fancy indexing
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz[[0, 2], [0, 2]]  # [1, 9] (elementos (0,0) y (2,2))
b[[1, 0, 1, 0], [0, 1, 2, 0]]  # [4.0, 2.0, 6.0, 1.5] (elementos (1,0), (0,1), (1,2), (0,0))
b[[1, 0, 1, 0]][:, [0, 1, 2, 0]]  # Seleccionar subconjunto de filas y columnas
matriz[[0, 2]]          # [[1, 2, 3], [7, 8, 9]] (filas 0 y 2)
matriz[:, [0, 2]]       # [[1, 3], [4, 6], [7, 9]] (columnas 0 y 2)

# Comparaciones elemento a elemento
a = np.array([1, 2, 3])
b = np.array([[1.5, 2, 3], [4, 5, 6]])
a == b                  # Comparación elemento a elemento (broadcasting)
a < 2                   # Comparación con escalar
np.array_equal(a, b)    # Comparación de arrays completos


False

## Selección de rangos de filas y columnas

En arrays 2D, usar slicing `[filas, columnas]`. El rango es `inicio:fin` (fin no incluido) o `inicio:fin:paso`.

In [3]:
import numpy as np

M = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# --- Rangos de filas ---
M[1:3]           # Filas 1 y 2 → array 2x4
M[0:2]           # Primeras 2 filas
M[2:]            # Desde fila 2 hasta el final
M[-2:]           # Últimas 2 filas
M[::2]           # Una de cada dos filas (0 y 2)

# --- Rangos de columnas ---
M[:, 1:3]        # Todas las filas, columnas 1 y 2
M[:, 0]          # Primera columna (1D)
M[:, 0:1]        # Primera columna (2D, shape (4,1))
M[:, -2:]        # Últimas 2 columnas
M[:, ::2]        # Columnas 0 y 2 (cada dos)

# --- Rango de filas y columnas a la vez ---
M[1:3, 1:4]      # Filas 1-2, columnas 1-3 (submatriz 2×3)
M[0:2, 0:2]      # Esquina superior izquierda 2x2
M[:2, -2:]       # Primeras 2 filas, últimas 2 columnas

# --- Un solo elemento, fila o columna ---
M[1, 2]          # Elemento fila 1, columna 2 (escalar)
M[1]             # Fila 1 (equivale a M[1, :])
M[:, 2]          # Columna 2

array([ 3,  7, 11, 15])

## Modificación de Arrays


In [4]:
arr = np.array([1, 2, 3, 4, 5])

# Modificar elementos
arr[0] = 10           # [10, 2, 3, 4, 5]
arr[1:3] = [20, 30]   # [10, 20, 30, 4, 5]

# Modificar con máscara booleana
arr[arr > 3] = 0      # [10, 20, 30, 0, 0]

# Copia vs vista - Demostración
arr_original = np.array([1, 2, 3, 4, 5])

# Vista: los cambios afectan al original
vista = arr_original[1:4]  # [2, 3, 4]
vista[0] = 99  # Modificar la vista
print(f"Array original después de modificar vista: {arr_original}")  # [1, 99, 3, 4, 5]

# Crear vista explícita
h = arr_original.view()  # Crear vista del array con los mismos datos

# Copia: los cambios NO afectan al original
arr_original2 = np.array([1, 2, 3, 4, 5])
copia = arr_original2[1:4].copy()  # Copia independiente
copia[0] = 99  # Modificar la copia
print(f"Array original después de modificar copia: {arr_original2}")  # [1, 2, 3, 4, 5] (sin cambios)

# Otras formas de copiar
np.copy(arr_original2)  # Crear copia del array
h = arr_original2.copy()  # Crear copia profunda del array

# Arrays 2D
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz[0, 0] = 10     # Modificar elemento
matriz[0] = [10, 20, 30]  # Modificar fila completa
matriz[:, 1] = 0      # Modificar columna completa


Array original después de modificar vista: [ 1 99  3  4  5]
Array original después de modificar copia: [1 2 3 4 5]


### Modificar sobrescribiendo y copias

Asignar con `=` modifica el array original (o una vista). Para conservar el original, trabajar con una **copia**. Reasignar la variable (`arr = arr[1:4]`) hace que apunte a un nuevo objeto.

In [5]:
import numpy as np

# --- Sobrescribir: la asignación con [ ] modifica el mismo array ---
a = np.array([1, 2, 3, 4, 5])
a[0] = 10              # Modifica a in-place → [10, 2, 3, 4, 5]
a[1:4] = 0            # Rango → [10, 0, 0, 0, 5]
a[a > 2] = -1         # Con máscara → [10, 0, -1, -1, -1]

# Reasignar la variable: apunta a un nuevo objeto (slice es una vista, cuidado)
a = np.array([1, 2, 3, 4, 5])
a = a[1:4]            # a ahora es [2, 3, 4]; el array [1,2,3,4,5] puede quedar sin referencia

# --- Copia: trabajar sin tocar el original ---
orig = np.array([1, 2, 3, 4, 5])
copia = orig.copy()   # Copia independiente
copia[0] = 99         # Solo cambia copia; orig no cambia
np.copy(orig)         # Otra forma de copiar

# Slice sin .copy() es una VISTA: modificar afecta al original
vista = orig[1:4]    # Vista, no copia
vista[0] = 99         # ¡También cambia orig!

# Copia de un slice para no modificar el original
copia_slice = orig[1:4].copy()
copia_slice[0] = 99   # orig sigue igual

## Eliminar filas, columnas y elementos

`np.delete(arr, índices, axis=None)` devuelve un **nuevo** array sin los elementos/filas/columnas indicados. No modifica el array original.

In [6]:
import numpy as np

# --- Array 1D: eliminar por índice ---
a = np.array([1, 2, 3, 4, 5])
np.delete(a, 2)              # Quitar índice 2 → [1, 2, 4, 5]
np.delete(a, [0, 4])         # Quitar índices 0 y 4 → [2, 3, 4]
np.delete(a, np.s_[1:4])     # Quitar índices 1, 2, 3 → [1, 5]
np.delete(a, slice(1, 4))    # Igual: slice(1,4) = índices 1,2,3

# --- Array 2D: eliminar FILAS (axis=0) ---
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
np.delete(M, 1, axis=0)       # Quitar fila 1 → array 3x3
np.delete(M, [0, 3], axis=0)  # Quitar filas 0 y 3 → array 2x3

# --- Array 2D: eliminar COLUMNAS (axis=1) ---
np.delete(M, 2, axis=1)      # Quitar columna 2 → array 4x2
np.delete(M, [0, 2], axis=1)  # Quitar columnas 0 y 2 → array 4x1

# --- Sin axis: se aplana y se elimina por posición (poco usado en 2D) ---
np.delete(M, 2)              # Elimina el 3.º elemento del array aplanado

# --- Alternativa: filtrar con máscara (crear nuevo array sin ciertas filas/columnas) ---
# "Eliminar" filas donde la primera columna sea par
M[np.where(M[:, 0] % 2 != 0)]   # Quedarse con filas con col0 impar
# "Eliminar" columnas por condición
M[:, M[0] < 8]                  # Columnas donde M[0] < 8

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Concatenación y División


In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
d = np.array([10, 15, 20])
e = np.array([[7, 7], [7, 7]])
f = np.array([[1, 0], [0, 1]])

# Concatenar
np.concatenate([a, d], axis=0)   # [1, 2, 3, 10, 15, 20]
np.concatenate([a, b])           # [1, 2, 3, 4, 5, 6]

# Apilar verticalmente (filas)
np.vstack([a, b])                # Apilar verticalmente (filas)
np.r_[e, f]                      # Stack arrays verticalmente (sintaxis alternativa)

# Apilar horizontalmente (columnas)
np.hstack([e, f])                # Apilar horizontalmente (columnas)
np.column_stack([a, d])          # Crear arrays apilados columna por columna
np.c_[a, d]                      # Sintaxis alternativa para column_stack

# Dividir
arr = np.array([1, 2, 3, 4, 5, 6])
np.hsplit(arr, 3)                # Dividir horizontalmente en 3 partes: [array([1, 2]), array([3, 4]), array([5, 6])]
np.split(arr, 3)                 # Dividir en 3 partes iguales
np.split(arr, [2, 4])            # Dividir en índices [2, 4]

# Para arrays 2D
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)
matriz = np.array([[1, 2], [3, 4], [5, 6]])
np.vsplit(c, 2)                  # Dividir verticalmente en 2 partes
np.vsplit(matriz, 3)             # Dividir verticalmente
np.hsplit(matriz, 2)             # Dividir horizontalmente


[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]

## Manipulación de Arrays

Transponer, cambiar forma, añadir/eliminar elementos.


In [8]:
# Transponer arrays
b = np.array([[1.5, 2, 3], [4, 5, 6]])
i = np.transpose(b)  # Permutar dimensiones del array
i.T                   # Transponer (equivalente)

# Cambiar forma
b.ravel()             # Aplanar el array (vista)
g = np.array([[1, 2], [3, 4], [5, 6]])
g.reshape(3, -1)      # 3 filas, columnas inferidas (2). -1 = "calcular automáticamente"

# Añadir/eliminar elementos
h = np.array([[1, 2, 3], [4, 5, 6]])
h.resize((2, 6))      # Cambiar tamaño del array (modifica in-place)
np.append(h, g)       # Añadir elementos al array
a = np.array([1, 2, 3])
np.insert(a, 1, 5)    # Insertar elementos en el array (insertar 5 en índice 1)
np.delete(a, [1])     # Eliminar elementos del array (eliminar elemento en índice 1)


array([1, 3])

## Ordenamiento de Arrays


In [9]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)

# Ordenar array
a.sort()              # Ordenar array in-place
np.sort(a)            # Retornar array ordenado (no modifica original)

# Ordenar por eje
c.sort(axis=0)         # Ordenar elementos del eje 0
np.sort(c, axis=1)    # Ordenar elementos del eje 1 (retorna copia)


array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])