# NumPy - Operaciones

Este notebook cubre las operaciones con arrays de NumPy: operaciones aritméticas, producto matricial, broadcasting y funciones de agregación.

## Operaciones Aritméticas


In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Operaciones elemento a elemento
a + b        # [6, 8, 10, 12]
a - b        # [-4, -4, -4, -4]
a * b        # [5, 12, 21, 32] (elemento a elemento, NO producto matricial)
a / b        # [0.2, 0.333..., 0.428..., 0.5]
a ** 2       # [1, 4, 9, 16]
a % 2        # [1, 0, 1, 0]

# Operaciones con escalares
a + 10       # [11, 12, 13, 14]
a * 2        # [2, 4, 6, 8]
a ** 2       # [1, 4, 9, 16]

# Funciones universales (ufuncs)
np.add(a, b)      # Suma
np.subtract(a, b) # Resta
np.multiply(a, b) # Multiplicación
np.divide(a, b)   # División
np.power(a, 2)    # Potencia
np.sqrt(a)        # Raíz cuadrada
np.exp(a)         # Exponencial
np.log(a)         # Logaritmo natural
np.sin(a)         # Seno
np.cos(a)         # Coseno
np.abs(a)         # Valor absoluto


array([1, 2, 3, 4])

## Producto Matricial


In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Producto matricial (dot product)
np.dot(a, b)      # Producto matricial
a @ b             # Operador @ (Python 3.5+)

# Producto elemento a elemento
a * b             # Multiplicación elemento a elemento

# Producto interno
np.inner(a, b)    # Producto interno

# Producto externo
np.outer([1, 2, 3], [4, 5, 6])

# Transpuesta
a.T               # Transpuesta
np.transpose(a)   # Transpuesta


array([[1, 3],
       [2, 4]])

## Broadcasting


In [3]:
# Broadcasting permite operaciones entre arrays de diferentes formas

# Ejemplo 1: Array 1D con escalar
arr = np.array([1, 2, 3, 4])
arr + 10  # [11, 12, 13, 14]

# Ejemplo 2: Array 2D con 1D
matriz = np.array([[1, 2, 3], [4, 5, 6]])  # (2, 3)
vector = np.array([10, 20, 30])            # (3,)
matriz + vector  # Broadcasting: [10,20,30] se replica para cada fila

# Ejemplo 3: Array 2D con columna
columna = np.array([[10], [20]])           # (2, 1)
matriz + columna  # Broadcasting: columna se replica para cada columna

# Reglas de broadcasting:
# 1. Si los arrays tienen diferente número de dimensiones, se añaden 1s a la izquierda
# 2. Arrays con tamaño 1 en alguna dimensión se comportan como si tuvieran ese tamaño
# 3. Arrays deben tener el mismo tamaño en dimensiones compatibles


array([[11, 12, 13],
       [24, 25, 26]])

## Funciones de Agregación


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Estadísticas básicas
np.sum(arr)           # 21 (suma total)
np.mean(arr)          # 3.5 (promedio)
np.std(arr)           # Desviación estándar
np.var(arr)           # Varianza
np.min(arr)           # 1 (mínimo)
np.max(arr)           # 6 (máximo)
np.median(arr)        # Mediana

# Por eje (axis)
np.sum(arr, axis=0)   # Suma por columnas: [5, 7, 9]
np.sum(arr, axis=1)   # Suma por filas: [6, 15]
np.mean(arr, axis=0)  # Promedio por columnas

# Otras funciones
np.prod(arr)          # Producto de todos los elementos
np.cumsum(arr)        # Suma acumulada
np.cumprod(arr)       # Producto acumulado
np.argmin(arr)        # Índice del mínimo
np.argmax(arr)        # Índice del máximo
np.any(arr > 3)       # True si algún elemento cumple condición
np.all(arr > 0)       # True si todos los elementos cumplen condición


np.True_